// Unit tests pentru generator-ul de calendar fiscal.
// Validăm aplicabilitatea regulilor pe scenarii reprezentative + calcule
// termene + idempotența merge-ului.

import { describe, expect, it } from "vitest"

import {
  generateFiscalCalendar,
  inferFiscalProfile,
  mergeAutoCalendarWithExisting,
  type AutoGeneratedFilingRecord,
} from "./fiscal-calendar-generator"
import {
  FISCAL_DECLARATION_RULES,
  applicableRules,
  countApplicableRules,
  groupRulesByCategory,
  __test_helpers,
  type FiscalOrgProfile,
} from "./fiscal-calendar-rules"
import type { FilingRecord } from "@/lib/compliance/filing-discipline"

const NOW = "2026-05-13T10:00:00.000Z"

// ── Profile fixtures ─────────────────────────────────────────────────────────

const SRL_MIC_PLATITOR_TVA: FiscalOrgProfile = {
  sector: "professional-services",
  employeeCount: "1-9",
  usesAITools: false,
  requiresEfactura: true,
  vatRegistered: true,
  cui: "RO12345678",
  completedAtISO: NOW,
  legalForm: "SRL",
  hasEmployees: false,
  hasIntraCommunityTransactions: false,
  isMicroenterprise: true,
  paysCorporateTax: false,
  saftCategory: "small",
}

const SRL_MARE_PLATITOR_TVA_CU_UE: FiscalOrgProfile = {
  ...SRL_MIC_PLATITOR_TVA,
  employeeCount: "50-249",
  hasEmployees: true,
  hasIntraCommunityTransactions: true,
  isMicroenterprise: false,
  paysCorporateTax: true,
  saftCategory: "medium",
  vatFrequency: "monthly",
}

const PFA_NEPLATITOR_TVA: FiscalOrgProfile = {
  ...SRL_MIC_PLATITOR_TVA,
  legalForm: "PFA",
  vatRegistered: false,
  requiresEfactura: false,
  isMicroenterprise: false,
  paysCorporateTax: false,
}

const SRL_NEPLATITOR_TVA: FiscalOrgProfile = {
  ...SRL_MIC_PLATITOR_TVA,
  vatRegistered: false,
  requiresEfactura: false,
}

// ── Catalog tests ────────────────────────────────────────────────────────────

describe("FISCAL_DECLARATION_RULES catalog", () => {
  it("are minim 20 reguli declarate", () => {
    expect(FISCAL_DECLARATION_RULES.length).toBeGreaterThanOrEqual(20)
  })

  it("fiecare regulă are cod, shortName, category și legal reference", () => {
    for (const rule of FISCAL_DECLARATION_RULES) {
      expect(rule.code).toBeTruthy()
      expect(rule.shortName).toBeTruthy()
      expect(rule.category).toMatch(/^(tva|impozit|muncitori|saft|efactura|raportari|registru)$/)
      expect(rule.legalReference).toBeTruthy()
    }
  })

  it("toate codurile sunt unice", () => {
    const codes = FISCAL_DECLARATION_RULES.map((r) => r.code)
    expect(new Set(codes).size).toBe(codes.length)
  })
})

// ── Applicability tests ──────────────────────────────────────────────────────

describe("applicableRules per profil", () => {
  it("SRL mic plătitor TVA → include D300, D394, D406, raport e-Factura B2C", () => {
    const codes = applicableRules(SRL_MIC_PLATITOR_TVA).map((r) => r.code)
    expect(codes).toContain("D300")
    expect(codes).toContain("D394")
    expect(codes).toContain("D406")
    expect(codes).toContain("EF-B2C-MONTHLY")
  })

  it("SRL mic plătitor TVA → NU include D390 (fără UE), D112 (fără angajați), Form 082 (nu e PFA)", () => {
    const codes = applicableRules(SRL_MIC_PLATITOR_TVA).map((r) => r.code)
    expect(codes).not.toContain("D390")
    expect(codes).not.toContain("D112")
    expect(codes).not.toContain("FORM-082")
  })

  it("SRL mare cu UE → include D390 (recapitulativă) + D112 (angajați)", () => {
    const codes = applicableRules(SRL_MARE_PLATITOR_TVA_CU_UE).map((r) => r.code)
    expect(codes).toContain("D390")
    expect(codes).toContain("D112")
    expect(codes).toContain("D101")
  })

  it("PFA → include D212 + Form 082 + D070, EXCLUDE D100, D101, D406", () => {
    const codes = applicableRules(PFA_NEPLATITOR_TVA).map((r) => r.code)
    expect(codes).toContain("D212")
    expect(codes).toContain("FORM-082")
    expect(codes).toContain("D070")
    expect(codes).not.toContain("D100")
    expect(codes).not.toContain("D101")
    expect(codes).not.toContain("D406")
    expect(codes).not.toContain("D300")
  })

  it("SRL neplătitor TVA → EXCLUDE D300, D394, D390", () => {
    const codes = applicableRules(SRL_NEPLATITOR_TVA).map((r) => r.code)
    expect(codes).not.toContain("D300")
    expect(codes).not.toContain("D394")
    expect(codes).not.toContain("D390")
  })

  it("countApplicableRules — SRL plătitor TVA cu angajați are mai multe decât PFA", () => {
    const countSrl = countApplicableRules(SRL_MARE_PLATITOR_TVA_CU_UE)
    const countPfa = countApplicableRules(PFA_NEPLATITOR_TVA)
    expect(countSrl).toBeGreaterThan(countPfa)
  })
})

// ── Frequency derivation tests ───────────────────────────────────────────────

describe("deriveVatFrequency", () => {
  const { deriveVatFrequency } = __test_helpers

  it("respectă override explicit", () => {
    const p: FiscalOrgProfile = {
      ...SRL_MIC_PLATITOR_TVA,
      vatFrequency: "monthly",
    }
    expect(deriveVatFrequency(p)).toBe("monthly")
  })

  it("UE → forțat lunar", () => {
    const p: FiscalOrgProfile = {
      ...SRL_MIC_PLATITOR_TVA,
      hasIntraCommunityTransactions: true,
      vatFrequency: undefined,
    }
    expect(deriveVatFrequency(p)).toBe("monthly")
  })

  it("primul an → trimestrial implicit", () => {
    const p: FiscalOrgProfile = {
      ...SRL_MIC_PLATITOR_TVA,
      isFirstYearOfActivity: true,
      vatFrequency: undefined,
    }
    expect(deriveVatFrequency(p)).toBe("quarterly")
  })

  it("CA mică (1-9 angajați) → trimestrial", () => {
    expect(deriveVatFrequency({ ...SRL_MIC_PLATITOR_TVA, vatFrequency: undefined })).toBe(
      "quarterly",
    )
  })

  it("CA mare (50-249 angajați) → lunar", () => {
    expect(
      deriveVatFrequency({ ...SRL_MARE_PLATITOR_TVA_CU_UE, vatFrequency: undefined, hasIntraCommunityTransactions: false }),
    ).toBe("monthly")
  })
})

// ── Due date computation tests ───────────────────────────────────────────────

describe("computeDueAfterPeriod (D300/D394 logic)", () => {
  const { computeDueAfterPeriod } = __test_helpers

  it("D300 lunar perioada 2026-05 → due 25 iunie 2026", () => {
    const iso = computeDueAfterPeriod("2026-05", 25)
    expect(iso).toBeTruthy()
    const d = new Date(iso!)
    expect(d.getUTCFullYear()).toBe(2026)
    expect(d.getUTCMonth()).toBe(5) // 0-indexed = iunie
    expect(d.getUTCDate()).toBe(25)
  })

  it("D300 trimestrial perioada 2026-Q1 → due 25 aprilie 2026", () => {
    const iso = computeDueAfterPeriod("2026-Q1", 25)
    expect(iso).toBeTruthy()
    const d = new Date(iso!)
    expect(d.getUTCFullYear()).toBe(2026)
    expect(d.getUTCMonth()).toBe(3) // 0-indexed = aprilie
    expect(d.getUTCDate()).toBe(25)
  })

  it("D300 lunar perioada 2026-12 → due 25 ianuarie 2027 (cross-year)", () => {
    const iso = computeDueAfterPeriod("2026-12", 25)
    expect(iso).toBeTruthy()
    const d = new Date(iso!)
    expect(d.getUTCFullYear()).toBe(2027)
    expect(d.getUTCMonth()).toBe(0) // ianuarie
    expect(d.getUTCDate()).toBe(25)
  })
})

// ── Generator tests ──────────────────────────────────────────────────────────

describe("generateFiscalCalendar — scenarii", () => {
  it("SRL mic plătitor TVA → generează minim 4 D300 trimestriale + 4 D394 + 12 raport e-Factura B2C în 12 luni", () => {
    const result = generateFiscalCalendar(SRL_MIC_PLATITOR_TVA, {
      monthsAhead: 12,
      nowISO: NOW,
    })

    const d300 = result.records.filter((r) => r.ruleCode === "D300")
    const d394 = result.records.filter((r) => r.ruleCode === "D394")
    const efb2c = result.records.filter((r) => r.ruleCode === "EF-B2C-MONTHLY")

    // Trimestrial Q3 + Q4 2026 + Q1 + Q2 + Q3 2027 (depinde de unde cad)
    expect(d300.length).toBeGreaterThanOrEqual(3)
    expect(d394.length).toBeGreaterThanOrEqual(3)
    expect(efb2c.length).toBeGreaterThanOrEqual(11)
  })

  it("PFA → generează Form 082 (deadline fix 26 mai 2026) dacă nu a trecut", () => {
    const earlierDate = "2026-05-01T10:00:00.000Z"
    const result = generateFiscalCalendar(PFA_NEPLATITOR_TVA, {
      monthsAhead: 3,
      nowISO: earlierDate,
      includeSituational: true,
    })

    // Form 082 e situațional cu termen fix, deci apare în situationalRules
    const situationalCodes = result.situationalRules.map((r) => r.code)
    expect(situationalCodes).toContain("FORM-082")
  })

  it("idempotent — re-rularea cu același input dă IDs identice", () => {
    const r1 = generateFiscalCalendar(SRL_MIC_PLATITOR_TVA, { monthsAhead: 6, nowISO: NOW })
    const r2 = generateFiscalCalendar(SRL_MIC_PLATITOR_TVA, { monthsAhead: 6, nowISO: NOW })
    const ids1 = r1.records.map((r) => r.id).sort()
    const ids2 = r2.records.map((r) => r.id).sort()
    expect(ids1).toEqual(ids2)
  })

  it("toate records au autoGenerated=true + ruleCode + legalReference", () => {
    const result = generateFiscalCalendar(SRL_MARE_PLATITOR_TVA_CU_UE, {
      monthsAhead: 3,
      nowISO: NOW,
    })
    for (const r of result.records) {
      expect(r.autoGenerated).toBe(true)
      expect(r.ruleCode).toBeTruthy()
      expect(r.legalReference).toBeTruthy()
      expect(r.id.startsWith("auto-cal-")).toBe(true)
      expect(r.note).toContain("[auto]")
    }
  })

  it("toate dueISO sunt în viitor (default includePastDue=false)", () => {
    const result = generateFiscalCalendar(SRL_MIC_PLATITOR_TVA, {
      monthsAhead: 12,
      nowISO: NOW,
    })
    const nowMs = new Date(NOW).getTime()
    for (const r of result.records) {
      expect(new Date(r.dueISO).getTime()).toBeGreaterThanOrEqual(nowMs)
    }
  })

  it("records sortate crescător după dueISO", () => {
    const result = generateFiscalCalendar(SRL_MIC_PLATITOR_TVA, {
      monthsAhead: 6,
      nowISO: NOW,
    })
    for (let i = 1; i < result.records.length; i++) {
      const prev = result.records[i - 1]?.dueISO ?? ""
      const cur = result.records[i]?.dueISO ?? ""
      expect(prev.localeCompare(cur)).toBeLessThanOrEqual(0)
    }
  })

  it("summary include counts corecte", () => {
    const result = generateFiscalCalendar(SRL_MIC_PLATITOR_TVA, {
      monthsAhead: 12,
      nowISO: NOW,
    })
    expect(result.summary.totalRecords).toBe(result.records.length)
    expect(result.summary.applicableRules).toBeGreaterThan(0)
    expect(result.summary.totalRules).toBeGreaterThanOrEqual(20)
  })
})

// ── Merge tests ──────────────────────────────────────────────────────────────

describe("mergeAutoCalendarWithExisting", () => {
  it("adaugă auto records noi pe state gol", () => {
    const auto = generateFiscalCalendar(SRL_MIC_PLATITOR_TVA, {
      monthsAhead: 3,
      nowISO: NOW,
    }).records

    const { merged, newCount, preservedFiledCount, preservedManualCount, refreshedCount } =
      mergeAutoCalendarWithExisting([], auto, NOW)

    expect(merged.length).toBe(auto.length)
    expect(newCount).toBe(auto.length)
    expect(refreshedCount).toBe(0)
    expect(preservedFiledCount).toBe(0)
    expect(preservedManualCount).toBe(0)
  })

  it("păstrează record manual cu același (type, period)", () => {
    const auto = generateFiscalCalendar(SRL_MIC_PLATITOR_TVA, {
      monthsAhead: 3,
      nowISO: NOW,
    }).records
    if (auto.length === 0) return

    const firstAuto = auto[0]!
    const manual: FilingRecord = {
      id: `manual-${firstAuto.type}-${firstAuto.period}`,
      type: firstAuto.type,
      period: firstAuto.period,
      status: "upcoming",
      dueISO: firstAuto.dueISO,
      note: "Manual input by user",
    }

    const { merged, preservedManualCount } = mergeAutoCalendarWithExisting(
      [manual],
      auto,
      NOW,
    )

    expect(preservedManualCount).toBe(1)
    expect(merged.find((m) => m.id === manual.id)).toBeDefined()
    expect(merged.find((m) => m.id === firstAuto.id)).toBeUndefined()
  })

  it("păstrează record cu status on_time / late (depus)", () => {
    const auto = generateFiscalCalendar(SRL_MIC_PLATITOR_TVA, {
      monthsAhead: 3,
      nowISO: NOW,
    }).records
    if (auto.length === 0) return

    const firstAuto = auto[0]!
    const filed: FilingRecord = {
      id: firstAuto.id, // ID auto, dar deja depus
      type: firstAuto.type,
      period: firstAuto.period,
      status: "on_time",
      dueISO: firstAuto.dueISO,
      filedAtISO: NOW,
    }

    const { merged, preservedFiledCount } = mergeAutoCalendarWithExisting(
      [filed],
      auto,
      NOW,
    )

    expect(preservedFiledCount).toBe(1)
    const inMerged = merged.find((m) => m.id === firstAuto.id)
    expect(inMerged?.status).toBe("on_time")
    expect(inMerged?.filedAtISO).toBe(NOW)
  })

  it("refresh auto vechi cu auto nou dacă același ID + status nu e filed", () => {
    const auto = generateFiscalCalendar(SRL_MIC_PLATITOR_TVA, {
      monthsAhead: 3,
      nowISO: NOW,
    }).records
    if (auto.length === 0) return

    const stale: AutoGeneratedFilingRecord = {
      ...auto[0]!,
      dueISO: "2024-01-01T00:00:00.000Z", // termen vechi
      status: "missing",
    }

    const { refreshedCount, merged } = mergeAutoCalendarWithExisting([stale], auto, NOW)
    expect(refreshedCount).toBe(1)
    const refreshed = merged.find((m) => m.id === auto[0]!.id)
    expect(refreshed?.dueISO).toBe(auto[0]!.dueISO) // updated to fresh due
  })
})

// ── inferFiscalProfile tests ─────────────────────────────────────────────────

describe("inferFiscalProfile", () => {
  it("aplică defaults conservatoare când câmpurile lipsesc", () => {
    const minimal: FiscalOrgProfile = {
      sector: "professional-services",
      employeeCount: "1-9",
      usesAITools: false,
      requiresEfactura: true,
      vatRegistered: true,
      completedAtISO: NOW,
    }
    const inferred = inferFiscalProfile(minimal)
    expect(inferred.legalForm).toBe("SRL")
    expect(inferred.hasEmployees).toBe(false)
    expect(inferred.hasIntraCommunityTransactions).toBe(false)
    expect(inferred.isMicroenterprise).toBe(true)
    expect(inferred.saftCategory).toBe("small")
  })

  it("respectă overrides explicite", () => {
    const minimal: FiscalOrgProfile = {
      sector: "professional-services",
      employeeCount: "10-49",
      usesAITools: false,
      requiresEfactura: true,
      vatRegistered: true,
      completedAtISO: NOW,
    }
    const inferred = inferFiscalProfile(minimal, {
      legalForm: "PFA",
      hasIntraCommunityTransactions: true,
    })
    expect(inferred.legalForm).toBe("PFA")
    expect(inferred.hasIntraCommunityTransactions).toBe(true)
  })
})

// ── groupRulesByCategory test ────────────────────────────────────────────────

describe("groupRulesByCategory", () => {
  it("grupează regulile pe 7 categorii", () => {
    const groups = groupRulesByCategory(FISCAL_DECLARATION_RULES)
    expect(Object.keys(groups).sort()).toEqual([
      "efactura",
      "impozit",
      "muncitori",
      "raportari",
      "registru",
      "saft",
      "tva",
    ])
    expect(groups.tva.length).toBeGreaterThan(0)
    expect(groups.impozit.length).toBeGreaterThan(0)
  })
})
