// Generator calendar fiscal — produce FilingRecord[] cu status "upcoming"
// pentru toate termenele aplicabile profilului firmei, pe o fereastră de N luni.
//
// Filosofia: NU inventăm date. Aplicăm regulile fiscale RO (CF, OUG-uri,
// Ordine ANAF) pe profilul dat și ieșim cu calendarul tău personalizat.
//
// Idempotent: ID-urile sunt deterministe (`auto-cal-${ruleCode}-${period}`),
// astfel re-rularea actualizează în loc să dubleze.
//
// Provenance: fiecare record are notă cu marker `[auto]` + temei legal, ca
// UI-ul să poată afișa badge "auto-detectat" + tooltip.

import {
  FISCAL_DECLARATION_RULES,
  applicableRules,
  type FiscalDeclarationRule,
  type FiscalOrgProfile,
  type RuleFrequency,
} from "@/lib/compliance/fiscal-calendar-rules"
import type {
  FilingRecord,
  FilingStatus,
  FilingType,
} from "@/lib/compliance/filing-discipline"

// ── Types ────────────────────────────────────────────────────────────────────

export type CalendarGenerationOptions = {
  /** Câte luni înainte generăm. Default 12. */
  monthsAhead?: number
  /** Data de referință (ISO). Default: acum. */
  nowISO?: string
  /** Includem situaționale (D700, D098, etc.)? Default false — sunt event-driven. */
  includeSituational?: boolean
  /** Includem termene deja trecute (înainte de nowISO)? Default false. */
  includePastDue?: boolean
}

export type CalendarEntryProvenance = {
  source: "auto-generated"
  ruleCode: string
  legalReference: string
  generatedAtISO: string
}

/** FilingRecord cu metadata provenance îmbogățită (auto-detectat). */
export type AutoGeneratedFilingRecord = FilingRecord & {
  /** Marker explicit pentru UI badge. */
  autoGenerated: true
  /** Codul regulii ANAF care a generat acest filing (D300, D406, etc.). */
  ruleCode: string
  /** Temei legal afișabil în tooltip. */
  legalReference: string
}

export type GenerationResult = {
  /** Records generate. */
  records: AutoGeneratedFilingRecord[]
  /** Reguli aplicabile dar fără perioade calculabile (situaționale). */
  situationalRules: FiscalDeclarationRule[]
  /** Sumar pentru UI. */
  summary: {
    totalRules: number
    applicableRules: number
    monthlyEntries: number
    quarterlyEntries: number
    annualEntries: number
    situationalEntries: number
    totalRecords: number
  }
}

// ── Helpers — generare perioade ──────────────────────────────────────────────

function pad2(n: number): string {
  return n < 10 ? `0${n}` : String(n)
}

/** Returnează lista lunilor între nowISO și nowISO + monthsAhead, format "YYYY-MM". */
function* iterateMonths(nowISO: string, monthsAhead: number): Generator<string> {
  const start = new Date(nowISO)
  const startYear = start.getUTCFullYear()
  const startMonth = start.getUTCMonth() + 1 // 1-12

  for (let i = 0; i < monthsAhead; i++) {
    let month = startMonth + i
    let year = startYear
    while (month > 12) {
      month -= 12
      year += 1
    }
    yield `${year}-${pad2(month)}`
  }
}

/** Returnează lista trimestrelor între nowISO și nowISO + monthsAhead. */
function* iterateQuarters(nowISO: string, monthsAhead: number): Generator<string> {
  const start = new Date(nowISO)
  const startYear = start.getUTCFullYear()
  const startMonth = start.getUTCMonth() + 1
  const startQuarter = Math.ceil(startMonth / 3)
  const quartersAhead = Math.ceil(monthsAhead / 3)

  const yielded = new Set<string>()
  for (let i = 0; i < quartersAhead + 1; i++) {
    let quarter = startQuarter + i
    let year = startYear
    while (quarter > 4) {
      quarter -= 4
      year += 1
    }
    const key = `${year}-Q${quarter}`
    if (yielded.has(key)) continue
    yielded.add(key)
    yield key
  }
}

/** Returnează anii relevanți (curent + următor). */
function* iterateYears(nowISO: string, monthsAhead: number): Generator<string> {
  const start = new Date(nowISO)
  const startYear = start.getUTCFullYear()
  const endYear = startYear + Math.ceil(monthsAhead / 12)
  for (let year = startYear; year <= endYear; year++) {
    yield String(year)
  }
}

// ── Status calculator ────────────────────────────────────────────────────────

/** Determină status filing — upcoming vs missing vs on_time vs late. */
function deriveStatus(dueISO: string, nowISO: string): FilingStatus {
  const dueMs = new Date(dueISO).getTime()
  const nowMs = new Date(nowISO).getTime()
  if (dueMs > nowMs) return "upcoming"
  return "missing"
}

// ── Generator principal ──────────────────────────────────────────────────────

export function generateFiscalCalendar(
  profile: FiscalOrgProfile,
  opts: CalendarGenerationOptions = {},
): GenerationResult {
  const monthsAhead = opts.monthsAhead ?? 12
  const nowISO = opts.nowISO ?? new Date().toISOString()
  const includeSituational = opts.includeSituational ?? false
  const includePastDue = opts.includePastDue ?? false

  const rules = applicableRules(profile)
  const records: AutoGeneratedFilingRecord[] = []
  const situationalRules: FiscalDeclarationRule[] = []

  let monthlyEntries = 0
  let quarterlyEntries = 0
  let annualEntries = 0
  let situationalEntries = 0

  for (const rule of rules) {
    const frequency = rule.frequencyFor(profile)

    if (frequency === "situational") {
      situationalRules.push(rule)
      if (!includeSituational) continue
      // Pentru situaționale fără termen recurent, generăm 0 records
      // dar regula apare în situationalRules pentru UI
      situationalEntries++
      continue
    }

    const periods =
      frequency === "monthly"
        ? Array.from(iterateMonths(nowISO, monthsAhead))
        : frequency === "quarterly"
          ? Array.from(iterateQuarters(nowISO, monthsAhead))
          : Array.from(iterateYears(nowISO, monthsAhead))

    for (const period of periods) {
      const dueISO = rule.computeDueDate(period, profile)
      if (!dueISO) continue

      // Skip termene din trecut (decât dacă explicit cerute)
      if (!includePastDue) {
        const dueMs = new Date(dueISO).getTime()
        const nowMs = new Date(nowISO).getTime()
        if (dueMs < nowMs) continue
      }

      // Mapăm doar dacă regula are FilingType existent în filing-discipline.
      // Restul (D100, D101, D112, etc.) le omitem temporar — necesită
      // extindere a FilingType. Marcăm în comentariu pentru viitor.
      if (!rule.filingType) continue

      const record: AutoGeneratedFilingRecord = {
        id: `auto-cal-${rule.code}-${period}`,
        type: rule.filingType,
        period,
        status: deriveStatus(dueISO, nowISO),
        dueISO,
        note: `[auto] ${rule.shortName} — ${rule.legalReference}`,
        autoGenerated: true,
        ruleCode: rule.code,
        legalReference: rule.legalReference,
      }
      records.push(record)

      if (frequency === "monthly") monthlyEntries++
      else if (frequency === "quarterly") quarterlyEntries++
      else if (frequency === "annual") annualEntries++
    }
  }

  // Sortăm crescător după dueISO pentru afișare ușoară
  records.sort((a, b) => a.dueISO.localeCompare(b.dueISO))

  return {
    records,
    situationalRules,
    summary: {
      totalRules: FISCAL_DECLARATION_RULES.length,
      applicableRules: rules.length,
      monthlyEntries,
      quarterlyEntries,
      annualEntries,
      situationalEntries,
      totalRecords: records.length,
    },
  }
}

// ── Reconciliere cu istoric existent ─────────────────────────────────────────

/**
 * Mergesz records auto-generate cu cele existente (manual/ERP/SAF-T).
 *
 * Reguli:
 *   1. Dacă există record manual (ID fără prefix `auto-cal-`) cu același
 *      `(type, period)`, păstrăm manualul, dropuim auto-ul.
 *   2. Dacă există record auto vechi cu același ID — actualizăm `dueISO`,
 *      `status`, `note` (data poate să se fi schimbat dacă opt-in la D098).
 *   3. Dacă există depunere efectivă (status `on_time`/`late`/`rectified`) pe
 *      auto-record, păstrăm depunerea (nu o suprascriem cu `upcoming`).
 */
export function mergeAutoCalendarWithExisting(
  existing: FilingRecord[],
  autoRecords: AutoGeneratedFilingRecord[],
  nowISO: string,
): {
  merged: FilingRecord[]
  newCount: number
  refreshedCount: number
  preservedManualCount: number
  preservedFiledCount: number
} {
  const existingByTypePeriod = new Map<string, FilingRecord>()
  for (const r of existing) {
    existingByTypePeriod.set(`${r.type}-${r.period}`, r)
  }

  const merged: FilingRecord[] = [...existing]
  let newCount = 0
  let refreshedCount = 0
  let preservedManualCount = 0
  let preservedFiledCount = 0

  for (const auto of autoRecords) {
    const key = `${auto.type}-${auto.period}`
    const existingRecord = existingByTypePeriod.get(key)

    if (!existingRecord) {
      // Caz nou — add
      merged.push(auto)
      newCount++
      continue
    }

    const isExistingAuto = existingRecord.id.startsWith("auto-cal-")
    const isExistingFiled =
      existingRecord.status === "on_time" ||
      existingRecord.status === "late" ||
      existingRecord.status === "rectified"

    if (isExistingFiled) {
      // User a depus deja — păstrăm depunerea
      preservedFiledCount++
      continue
    }

    if (!isExistingAuto) {
      // Manual — păstrăm
      preservedManualCount++
      continue
    }

    // Existing e auto-generated + nu e depus → refresh status + dueISO
    const idx = merged.findIndex((m) => m.id === existingRecord.id)
    if (idx >= 0) {
      merged[idx] = {
        ...existingRecord,
        dueISO: auto.dueISO,
        status: deriveStatus(auto.dueISO, nowISO),
        note: auto.note ?? existingRecord.note,
      }
      refreshedCount++
    }
  }

  return {
    merged,
    newCount,
    refreshedCount,
    preservedManualCount,
    preservedFiledCount,
  }
}

// ── Helper pentru UI / API: returnează profile inferat din OrgProfile minim ──

/**
 * Construiește un FiscalOrgProfile dintr-un OrgProfile minim, aplicând
 * defaults conservatoare pentru câmpurile lipsă.
 */
export function inferFiscalProfile(
  base: FiscalOrgProfile,
  overrides?: Partial<FiscalOrgProfile>,
): FiscalOrgProfile {
  return {
    ...base,
    legalForm: overrides?.legalForm ?? base.legalForm ?? "SRL",
    hasEmployees: overrides?.hasEmployees ?? base.hasEmployees ?? false,
    hasIntraCommunityTransactions:
      overrides?.hasIntraCommunityTransactions ??
      base.hasIntraCommunityTransactions ??
      false,
    isMicroenterprise: overrides?.isMicroenterprise ?? base.isMicroenterprise ?? true,
    paysCorporateTax: overrides?.paysCorporateTax ?? base.paysCorporateTax ?? false,
    isFirstYearOfActivity:
      overrides?.isFirstYearOfActivity ?? base.isFirstYearOfActivity ?? false,
    saftCategory: overrides?.saftCategory ?? base.saftCategory ?? "small",
  }
}
