// V6 — Agent Orchestrator
// Executes agents, applies auto-actions (notifications, findings),
// logs results, respects human-in-the-loop levels.

import { normalizeComplianceState } from "@/lib/compliance/engine"
import { readStateForOrg } from "@/lib/server/mvp-store"
import { createNotification } from "@/lib/server/notifications-store"
import { safeAppendRun } from "@/lib/server/agent-run-store"
import { trackEvent } from "@/lib/server/analytics"
import { runComplianceMonitor } from "@/lib/compliance/agent-compliance-monitor"
import { runFiscalSensor } from "@/lib/compliance/agent-fiscal-sensor"
import { runDocumentAgent } from "@/lib/compliance/agent-document"
import { runVendorRiskAgent } from "@/lib/compliance/agent-vendor-risk"
import { runRegulatoryRadar } from "@/lib/compliance/agent-regulatory-radar"
import { listPendingActions, markAutoExecuted } from "@/lib/server/approval-queue"
import { resolvePolicy } from "@/lib/server/autonomy-resolver"
import { dispatchAutoExecutedAction } from "@/lib/server/semi-auto-dispatcher"
import type { EurLexDocument } from "@/lib/server/eurlex-client"
import type { DnscAnnouncement } from "@/lib/server/dnsc-monitor"
import type { AgentType, AgentOutput } from "@/lib/compliance/agentic-engine"

export type AgentExecutionOptions = {
  externalSources?: {
    eurLexDocs?: EurLexDocument[]
    dnscAnnouncements?: DnscAnnouncement[]
  }
}

/** Human-friendly prefixes for notifications generated by agents. */
const AGENT_NOTIF_PREFIX: Record<AgentType, string> = {
  fiscal_sensor: "Compli a verificat facturile",
  compliance_monitor: "Am detectat o schimbare",
  document: "Ți-am pregătit un document",
  vendor_risk: "Am verificat furnizorii",
  regulatory_radar: "Schimbare legislativă detectată",
}
import { safeListReviews } from "@/lib/server/vendor-review-store"
import { readNis2State, updateIncident } from "@/lib/server/nis2-store"
import type { Nis2Incident } from "@/lib/server/nis2-store"

export type OrchestratorResult = {
  orgId: string
  agentsRun: AgentType[]
  outputs: AgentOutput[]
  totalActions: number
  totalIssues: number
  executedAtISO: string
}

/**
 * Execute a single agent for an org.
 * Applies level-1 auto-actions (notifications).
 * Returns the agent output.
 */
export async function executeAgent(
  orgId: string,
  agentType: AgentType,
  options?: AgentExecutionOptions,
): Promise<AgentOutput> {
  const nowISO = new Date().toISOString()

  if (agentType === "compliance_monitor") {
    const rawState = await readStateForOrg(orgId)
    if (!rawState) {
      return makeEmptyOutput(agentType, "Nicio stare de conformitate pentru această organizație.")
    }
    const state = normalizeComplianceState(rawState)
    const vendorReviews = await safeListReviews(orgId)

    const output = runComplianceMonitor({
      orgId,
      state,
      vendorReviews,
      nowISO,
    })

    // Apply level-1 auto-actions: notifications
    await applyAutoActions(orgId, output)
    await safeAppendRun(orgId, output)
    void trackEvent(orgId, "agent_run" as never, {
      agent: agentType,
      issues: output.metrics?.issuesFound ?? 0,
    })

    return output
  }

  if (agentType === "fiscal_sensor") {
    const rawState = await readStateForOrg(orgId)
    if (!rawState) {
      return makeEmptyOutput(agentType, "Nicio stare de conformitate pentru această organizație.")
    }
    const state = normalizeComplianceState(rawState)

    // Get e-Factura signals from state
    const signals = (state as Record<string, unknown>).efacturaSignals as
      | import("@/lib/compliance/efactura-risk").EFacturaInvoiceSignal[]
      | undefined

    const output = runFiscalSensor({
      orgId,
      state,
      signals: signals ?? [],
      nowISO,
    })

    await applyAutoActions(orgId, output)
    await safeAppendRun(orgId, output)
    void trackEvent(orgId, "agent_run" as never, {
      agent: agentType,
      issues: output.metrics?.issuesFound ?? 0,
    })

    return output
  }

  if (agentType === "document") {
    const rawState = await readStateForOrg(orgId)
    if (!rawState) {
      return makeEmptyOutput(agentType, "Nicio stare de conformitate pentru această organizație.")
    }
    const state = normalizeComplianceState(rawState)

    const output = runDocumentAgent({
      orgId,
      state,
      nowISO,
    })

    await applyAutoActions(orgId, output)
    await safeAppendRun(orgId, output)
    void trackEvent(orgId, "agent_run" as never, {
      agent: agentType,
      issues: output.metrics?.issuesFound ?? 0,
    })

    return output
  }

  if (agentType === "vendor_risk") {
    const rawState = await readStateForOrg(orgId)
    if (!rawState) {
      return makeEmptyOutput(agentType, "Nicio stare de conformitate pentru această organizație.")
    }
    const state = normalizeComplianceState(rawState)
    const vendorReviews = await safeListReviews(orgId)

    const output = runVendorRiskAgent({
      orgId,
      state,
      vendorReviews,
      nowISO,
    })

    await applyAutoActions(orgId, output)
    await safeAppendRun(orgId, output)
    void trackEvent(orgId, "agent_run" as never, {
      agent: agentType,
      issues: output.metrics?.issuesFound ?? 0,
    })

    return output
  }

  if (agentType === "regulatory_radar") {
    const rawState = await readStateForOrg(orgId)
    if (!rawState) {
      return makeEmptyOutput(agentType, "Nicio stare de conformitate pentru această organizație.")
    }
    const state = normalizeComplianceState(rawState)

    const output = runRegulatoryRadar({
      orgId,
      state,
      nowISO,
      externalSources: options?.externalSources,
    })

    await applyAutoActions(orgId, output)
    await safeAppendRun(orgId, output)
    void trackEvent(orgId, "agent_run" as never, {
      agent: agentType,
      issues: output.metrics?.issuesFound ?? 0,
    })

    return output
  }

  // Placeholder for future agents
  return makeEmptyOutput(agentType, `Agentul "${agentType}" nu este încă implementat.`)
}

/**
 * Execute multiple agents for an org (e.g., daily cron).
 */
export async function executeAgents(
  orgId: string,
  agentTypes: AgentType[],
): Promise<OrchestratorResult> {
  const outputs: AgentOutput[] = []

  for (const agentType of agentTypes) {
    try {
      const output = await executeAgent(orgId, agentType)
      outputs.push(output)
    } catch (error) {
      outputs.push({
        agentType,
        runId: `run-${agentType}-error`,
        status: "failed",
        actions: [],
        confidence: 0,
        reasoning: `Eroare la execuția agentului: ${error instanceof Error ? error.message : "necunoscută"}`,
        startedAtISO: new Date().toISOString(),
        completedAtISO: new Date().toISOString(),
        error: error instanceof Error ? error.message : "unknown",
      })
    }
  }

  // A6 — Check incident SLA timers after running agents
  try {
    await checkIncidentTimers(orgId)
  } catch {
    // Timer check failure shouldn't block orchestrator result
  }

  return {
    orgId,
    agentsRun: agentTypes,
    outputs,
    totalActions: outputs.reduce((s, o) => s + o.actions.length, 0),
    totalIssues: outputs.reduce((s, o) => s + (o.metrics?.issuesFound ?? 0), 0),
    executedAtISO: new Date().toISOString(),
  }
}

// ── A6 — Incident SLA Timer Alerts ──────────────────────────────────────────

/**
 * Check all open NIS2 incidents for SLA deadlines.
 * Sends in-app notifications at 50% and 80% of SLA time elapsed.
 * SLA: critical = 24h, high = 72h, medium/low = 72h.
 */
export async function checkIncidentTimers(orgId: string): Promise<number> {
  const nis2State = await readNis2State(orgId)
  const incidents = nis2State.incidents
  let alertsSent = 0

  for (const incident of incidents) {
    if (incident.status === "closed") continue
    if (incident.resolvedAtISO) continue

    const slaHours = incident.severity === "critical" ? 24 : 72
    const detectedAt = new Date(incident.detectedAtISO).getTime()
    const elapsed = (Date.now() - detectedAt) / 3_600_000
    const percent = (elapsed / slaHours) * 100
    const hoursRemaining = Math.max(0, slaHours - elapsed)

    // 50% alert
    if (percent >= 50 && !incident.alert50SentAtISO) {
      await sendIncidentSlaAlert(orgId, incident, 50, hoursRemaining)
      await updateIncident(orgId, incident.id, {
        alert50SentAtISO: new Date().toISOString(),
      })
      alertsSent++
    }

    // 80% alert
    if (percent >= 80 && !incident.alert80SentAtISO) {
      await sendIncidentSlaAlert(orgId, incident, 80, hoursRemaining)
      await updateIncident(orgId, incident.id, {
        alert80SentAtISO: new Date().toISOString(),
      })
      alertsSent++
    }
  }

  return alertsSent
}

async function sendIncidentSlaAlert(
  orgId: string,
  incident: Nis2Incident,
  percent: number,
  hoursRemaining: number
): Promise<void> {
  const urgency = percent >= 80 ? "URGENT" : "ATENȚIE"
  const hours = Math.round(hoursRemaining)

  await createNotification(orgId, {
    type: "finding_new",
    title: `${urgency}: Incident "${incident.title}" — ${percent}% din SLA consumat`,
    message:
      `Incidentul NIS2 "${incident.title}" (${incident.severity}) a consumat ${percent}% ` +
      `din termenul SLA. Mai ai ~${hours}h pentru rezolvare/raportare DNSC.`,
    linkTo: "/dashboard/actiuni/remediere",
  }).catch(() => {
    // Notification failure shouldn't block timer check
  })
}

// ── Semi-auto sweeper ────────────────────────────────────────────────────────

/**
 * Sweep pending actions whose semi-auto window (24h) has elapsed.
 * For each: re-check policy. If still "semi", mark auto_executed.
 * Called from the daily cron (agent-orchestrator cron).
 * NEVER touches submit_anaf (locked to manual).
 */
export async function sweepSemiAutoActions(orgId: string): Promise<number> {
  const now = new Date()
  const nowISO = now.toISOString()
  let executed = 0

  try {
    const pending = await listPendingActions(orgId, { status: ["pending"], limit: 200 })

    for (const action of pending) {
      // Only process actions that have an expiry set (semi-auto have expiresAt)
      if (!action.expiresAt) continue

      // Only process if the 24h window has elapsed
      if (action.expiresAt > nowISO) continue

      // Never auto-execute submit_anaf — locked override
      if (action.actionType === "submit_anaf") continue

      // Re-verify policy is still "semi" (user may have changed settings)
      const userId = action.userId ?? "system"
      const policy = await resolvePolicy({
        userId,
        orgId,
        actionType: action.actionType,
        riskLevel: action.riskLevel,
      }).catch(() => "manual" as const)

      if (policy !== "semi") continue

      // Dispatch the real side-effect (resolve finding, etc.)
      const dispatchResult = await dispatchAutoExecutedAction(action)

      await markAutoExecuted(orgId, action.id, {
        reason: "Semi-auto window elapsed without rejection",
        sweptAtISO: nowISO,
        dispatched: dispatchResult.executed,
        dispatchDetail: dispatchResult.detail,
      })

      // Notify the org owner
      await createNotification(orgId, {
        type: "info",
        title: `Acțiune auto-executată: ${action.actionType}`,
        message:
          `"${action.diffSummary ?? action.explanation ?? action.actionType}" ` +
          `a fost executată automat după 24h fără respingere.` +
          (dispatchResult.executed ? ` Rezultat: ${dispatchResult.detail}` : ""),
        linkTo: "/dashboard/approvals",
      }).catch(() => {})

      executed++
    }
  } catch {
    // Sweeper failure shouldn't block other orchestrator work
  }

  return executed
}

// ── Helpers ──────────────────────────────────────────────────────────────────

async function applyAutoActions(orgId: string, output: AgentOutput): Promise<void> {
  const autoActions = output.actions.filter((a) => a.autoApplied)

  for (const action of autoActions) {
    if (action.type === "notification_sent" || action.type === "escalation_raised") {
      await createNotification(orgId, {
        type: action.type === "escalation_raised" ? "finding_new" : "info",
        title: `${AGENT_NOTIF_PREFIX[output.agentType] ?? "Compli a verificat"}: ${action.description.slice(0, 80)}`,
        message: action.description,
        linkTo: action.targetId ? `/dashboard/scan` : undefined,
      }).catch(() => {
        // Notification failure shouldn't block agent execution
      })
    }
  }
}

function makeEmptyOutput(agentType: AgentType, reasoning: string): AgentOutput {
  return {
    agentType,
    runId: `run-${agentType}-skip`,
    status: "completed",
    actions: [],
    confidence: 1,
    reasoning,
    startedAtISO: new Date().toISOString(),
    completedAtISO: new Date().toISOString(),
    metrics: { itemsScanned: 0, issuesFound: 0, actionsAutoApplied: 0, actionsPendingApproval: 0 },
  }
}
