// Unified preventive fiscal scan — rulează toate detectoarele preventive
// disponibile (filings deadline radar, cert expiry, frequency mismatch,
// consistency, sequence gap dacă date prezente) într-un singur swoop și
// întoarce rezultat agregat + listă de findings new gata pentru persistare.
//
// "Preventiv" = catch BEFORE ANAF returns a rejection. Spre deosebire de
// SPV signals (reactive, post-fact), aceste detectoare lucrează pe state-ul
// local: orgProfile, filingRecords, certSpvRecords. Nu necesită token ANAF
// OAuth valid — funcționează în orice mediu (mock/test/prod).
//
// Pure-ish: funcția primește state + nowISO + opts, întoarce rezultat.
// Persistarea findings → state e responsabilitatea caller-ului (route handler).

import type {
  ComplianceState,
  ScanFinding,
} from "@/lib/compliance/types"
import {
  buildOverdueFilingFindings,
  checkFilingConsistency,
  FILING_TYPE_LABELS,
  generateFilingReminders,
  type ConsistencyIssue,
  type FilingRecord,
  type FilingReminder,
} from "@/lib/compliance/filing-discipline"
import {
  buildSnapshot as buildCertSnapshot,
  recomputeStatus as recomputeCertStatus,
  daysUntilExpiry as certDaysUntilExpiry,
  type CertSpvRecord,
  type CertSpvSnapshot,
} from "@/lib/compliance/cert-spv-tracker"
import {
  detectExpectedFrequency,
  detectFrequencyMismatches,
  type FrequencyDetection,
  type FrequencyMismatch,
} from "@/lib/compliance/declaration-frequency-detector"
import { makeResolution } from "@/lib/compliance/finding-resolution"
import {
  generateFiscalCalendar,
  inferFiscalProfile,
  mergeAutoCalendarWithExisting,
  type AutoGeneratedFilingRecord,
} from "@/lib/compliance/fiscal-calendar-generator"
import type { FiscalOrgProfile } from "@/lib/compliance/fiscal-calendar-rules"

// ── Types ────────────────────────────────────────────────────────────────────

type StateWithFiscal = ComplianceState & {
  filingRecords?: FilingRecord[]
  certSpvRecords?: CertSpvRecord[]
}

export type PreventiveScanInput = {
  state: StateWithFiscal
  nowISO: string
  /**
   * Dacă true, auto-populează calendarul fiscal din profilul firmei înainte
   * de a rula detectoarele. Default: true. Vezi `generateFiscalCalendar`.
   */
  autoPopulateCalendar?: boolean
  /**
   * Câte luni înainte generăm calendarul. Default 12.
   */
  calendarMonthsAhead?: number
}

export type PreventiveScanSummary = {
  totalChecks: number
  criticalCount: number
  warningCount: number
  infoCount: number
  newFindingsCount: number
}

export type PreventiveScanResult = {
  scanId: string
  scannedAtISO: string
  summary: PreventiveScanSummary
  expectedFrequency: FrequencyDetection
  frequencyMismatches: FrequencyMismatch[]
  filingReminders: FilingReminder[]
  overdueFindings: ScanFinding[]
  frequencyFindings: ScanFinding[]
  certFindings: ScanFinding[]
  certSnapshot: CertSpvSnapshot | null
  consistencyIssues: ConsistencyIssue[]
  /** Aggregated list of NEW findings (overdueFindings + frequencyFindings + certFindings) */
  newFindings: ScanFinding[]
  /** Calendar auto-populat (dacă autoPopulateCalendar=true). */
  calendarAutoFill: {
    enabled: boolean
    applicableRulesCount: number
    autoRecordsGenerated: number
    newCount: number
    refreshedCount: number
    preservedManualCount: number
    preservedFiledCount: number
    /** Filings care s-au adăugat în state (pentru ca caller-ul să persistă). */
    mergedFilings: FilingRecord[]
  }
}

// ── Helpers — convertesc detectorii care nu returnează direct ScanFinding ────

function estimateAnnualRevenue(state: StateWithFiscal): number | null {
  const employeeCount = state.orgProfile?.employeeCount
  if (employeeCount === "1-9") return 200_000
  if (employeeCount === "10-49") return 800_000
  if (employeeCount === "50-249") return 5_000_000
  if (employeeCount === "250+") return 30_000_000
  return null
}

export function buildFrequencyMismatchFindings(
  mismatches: FrequencyMismatch[],
  expected: FrequencyDetection,
  nowISO: string,
): ScanFinding[] {
  if (mismatches.length === 0) return []

  // Grupăm pe tip + frecvență — o singură finding per (type, filedAs).
  const groups = new Map<string, FrequencyMismatch[]>()
  for (const m of mismatches) {
    const key = `${m.filingType}-${m.filedAsFrequency}`
    const list = groups.get(key) ?? []
    list.push(m)
    groups.set(key, list)
  }

  const findings: ScanFinding[] = []
  for (const [key, list] of groups.entries()) {
    const sample = list[0]
    if (!sample) continue
    const typeLabel = FILING_TYPE_LABELS[sample.filingType]
    const expectedLabel = sample.detectedFrequency === "monthly" ? "LUNAR" : "TRIMESTRIAL"
    const actualLabel = sample.filedAsFrequency === "monthly" ? "LUNAR" : "TRIMESTRIAL"

    findings.push({
      id: `freq-mismatch-${key}`,
      findingTypeId: "FREQUENCY-MISMATCH",
      title: `Frecvență ${typeLabel} incorectă — depui ${actualLabel}, ar trebui ${expectedLabel}`,
      detail:
        `Detectat pe ${list.length} declarații (${typeLabel}). ${expected.reason}` +
        ` Perioade afectate: ${list
          .slice(0, 5)
          .map((m) => m.period)
          .join(", ")}${list.length > 5 ? "…" : ""}.`,
      category: "E_FACTURA",
      severity: "high",
      risk: "high",
      principles: [],
      createdAtISO: nowISO,
      sourceDocument: "Frequency Detector",
      scanId: `preventive-${nowISO.split("T")[0]}`,
      legalReference: "Cod Fiscal Art. 322",
      impactSummary:
        `ANAF eroare A9.6: ${typeLabel} depusă pe frecvență greșită. Risc respingere + amendă contravențională (1.000-5.000 RON) + obligație de rectificare.`,
      remediationHint:
        `Depune cerere de schimbare frecvență (D098 sau Notificare) pentru ${typeLabel}. Apoi re-depune declarațiile pe frecvența corectă.`,
      resolution: makeResolution(
        `${typeLabel} depusă ca ${actualLabel} pentru ${list.length} perioade — corect: ${expectedLabel}`,
        "Frecvența incorectă atrage respingerea ANAF + amenzi. Schimbarea se face o singură dată/an la cerere.",
        `Depune D098 pentru schimbare frecvență, apoi rectifică declarațiile pe noua frecvență.`,
        {
          humanStep: "Verifică pragul CA cu contabilul, depune D098, re-depune declarațiile.",
          closureEvidence: "Confirmare ANAF D098 + dovezi rectificative.",
          revalidation: "Re-rulează scanul preventiv după ce ANAF confirmă schimbarea.",
        },
      ),
    })
  }
  return findings
}

export function buildCertExpiryFindings(
  certs: CertSpvRecord[],
  nowISO: string,
): ScanFinding[] {
  const findings: ScanFinding[] = []
  for (const raw of certs) {
    const r = recomputeCertStatus(raw, nowISO)
    if (
      r.status !== "expiring_critical" &&
      r.status !== "expired" &&
      r.status !== "expiring_soon" &&
      r.status !== "unauthorized" &&
      r.status !== "renewed_pending"
    ) {
      continue
    }
    const days = certDaysUntilExpiry(r.validUntilISO, nowISO)
    const severity =
      r.status === "expired" || r.status === "unauthorized"
        ? "critical"
        : r.status === "expiring_critical"
          ? "high"
          : "medium"

    const isUnauthorized = r.status === "unauthorized"
    const isExpired = r.status === "expired"
    const isRenewedPending = r.status === "renewed_pending"

    findings.push({
      id: `cert-expiry-${r.id}`,
      findingTypeId: isExpired || isUnauthorized ? "CERT-EXPIRED" : "CERT-EXPIRING",
      title: isUnauthorized
        ? `Certificat digital "${r.ownerName}" — UTILIZATOR NEAUTORIZAT în SPV`
        : isExpired
          ? `Certificat digital "${r.ownerName}" EXPIRAT (client ${r.clientName})`
          : isRenewedPending
            ? `Certificat digital "${r.ownerName}" — reînnoit, în grace ANAF SPV (client ${r.clientName})`
            : `Certificat digital "${r.ownerName}" expiră în ${days} zile (client ${r.clientName})`,
      detail: isUnauthorized
        ? `Cert ${r.certSerial} (titular ${r.ownerName}) — ANAF SPV răspunde "Utilizator neautorizat". Grace period post-renewal poate dura până la 17 zile. Verifică dacă a fost reînrolat.`
        : isExpired
          ? `Cert ${r.certSerial} (titular ${r.ownerName}) — expirat de ${Math.abs(days)} zile. Toate facturile pentru clientul ${r.clientName} (CIF ${r.clientCif}) sunt blocate.`
          : isRenewedPending
            ? `Cert ${r.certSerial} (titular ${r.ownerName}) — reînnoit recent, în grace period ANAF (≤14 zile). Ultima verificare SPV: NEAUTORIZAT. Monitorizare automată activă.`
            : `Cert ${r.certSerial} (titular ${r.ownerName}) expiră în ${days} zile. Reînnoiește acum pentru a evita blocarea transmiterii.`,
      category: "E_FACTURA",
      severity,
      risk: severity === "critical" || severity === "high" ? "high" : "low",
      principles: [],
      createdAtISO: nowISO,
      sourceDocument: `Cert SPV — ${r.clientName}`,
      scanId: `preventive-${nowISO.split("T")[0]}`,
      legalReference: "OUG 38/2020 · Lege 455/2001",
      impactSummary: isUnauthorized
        ? "Toate transmiterile e-Factura prin acest cert sunt blocate. ANAF respinge fără mesaj clar."
        : isExpired
          ? "Imposibil de trimis e-Factura prin acest cert. Risc amendă 15% din valoarea facturii (Art. 13^1)."
          : isRenewedPending
            ? "ANAF SPV poate respinge transmiterile până la confirmarea reînrolării (≤48h tipic, ocazional 17 zile)."
            : "Fără reînnoire, transmiterile e-Factura se blochează la data expirării.",
      remediationHint: isUnauthorized
        ? "Re-înrolă certul în SPV ANAF (logincert.anaf.ro → Setări → Certificat). Așteaptă confirmare 24-48h."
        : isRenewedPending
          ? "Monitorizează zilnic. Dacă persistă peste 14 zile, contactează ANAF (021.387.10.00) cu cererea de re-înrolare."
          : "Achiziționează cert nou de la CertSign/DigiSign/TransSped, înrolă-l în SPV ANAF.",
    })
  }
  return findings
}

export function buildUpcomingFilingFindings(
  reminders: FilingReminder[],
  nowISO: string,
): ScanFinding[] {
  // Doar escalation (≤3 zile) devine finding. Restul rămân reminder-uri vizuale.
  const findings: ScanFinding[] = []
  for (const reminder of reminders) {
    if (reminder.escalationLevel !== "escalation") continue
    const typeLabel = FILING_TYPE_LABELS[reminder.filingType]
    findings.push({
      id: `filing-upcoming-${reminder.filingId}`,
      findingTypeId: "FILING-DUE-SOON",
      title: `URGENT: ${typeLabel} (${reminder.period}) — termen în ${reminder.daysUntilDue} zile`,
      detail: reminder.message,
      category: "E_FACTURA",
      severity: "high",
      risk: "high",
      principles: ["accountability"],
      createdAtISO: nowISO,
      sourceDocument: `${typeLabel} ${reminder.period}`,
      scanId: `preventive-${nowISO.split("T")[0]}`,
      legalReference: "Cod Procedură Fiscală Art. 336-338",
      impactSummary: `Nedepunere la termen → penalitate 0.06%/zi + amendă 1.000-5.000 RON.`,
      remediationHint: `Pregătește și depune ${typeLabel} pentru ${reminder.period} prin SPV ANAF înainte de ${reminder.dueISO.slice(0, 10)}.`,
    })
  }
  return findings
}

// ── Runner principal ─────────────────────────────────────────────────────────

export function runPreventiveScan(input: PreventiveScanInput): PreventiveScanResult {
  const { state, nowISO } = input
  const autoPopulateCalendar = input.autoPopulateCalendar !== false // default true
  const calendarMonthsAhead = input.calendarMonthsAhead ?? 12
  const scanId = `preventive-${nowISO.split("T")[0]}-${Date.now().toString(36)}`

  // 0. Auto-populare calendar fiscal — derivăm termenele aplicabile din
  // profilul firmei (CUI, TVA, angajați, etc.) folosind catalogul de 26
  // declarații ANAF. Fiecare termen e marcat `[auto]` în note + are
  // provenance vizibil în UI. NU inventăm date — doar aplicăm regulile
  // fiscale RO publice pe profilul concret al firmei.
  const existingFilings: FilingRecord[] = state.filingRecords ?? []
  let mergedFilings: FilingRecord[] = existingFilings
  let autoRecordsGenerated = 0
  let applicableRulesCount = 0
  let newCount = 0
  let refreshedCount = 0
  let preservedManualCount = 0
  let preservedFiledCount = 0

  if (autoPopulateCalendar && state.orgProfile) {
    const fiscalProfile = inferFiscalProfile(state.orgProfile as FiscalOrgProfile)
    const generation = generateFiscalCalendar(fiscalProfile, {
      monthsAhead: calendarMonthsAhead,
      nowISO,
    })
    autoRecordsGenerated = generation.records.length
    applicableRulesCount = generation.summary.applicableRules

    const mergeResult = mergeAutoCalendarWithExisting(
      existingFilings,
      generation.records,
      nowISO,
    )
    mergedFilings = mergeResult.merged
    newCount = mergeResult.newCount
    refreshedCount = mergeResult.refreshedCount
    preservedManualCount = mergeResult.preservedManualCount
    preservedFiledCount = mergeResult.preservedFiledCount
  }

  // 1. Frecvență declarații
  const annualRevenueRon = estimateAnnualRevenue(state)
  const expectedFrequency = detectExpectedFrequency({
    annualRevenueRon,
    hasIntraCommunityTransactions: false,
    isFirstYearOfActivity: false,
  })
  const filings: FilingRecord[] = mergedFilings
  const frequencyMismatches = detectFrequencyMismatches(filings, expectedFrequency)
  const frequencyFindings = buildFrequencyMismatchFindings(
    frequencyMismatches,
    expectedFrequency,
    nowISO,
  )

  // 2. Filings deadline radar (overdue → findings, upcoming → reminders)
  const overdueFindings = buildOverdueFilingFindings(filings, nowISO)
  const filingReminders = generateFilingReminders(filings, nowISO)
  const upcomingFindings = buildUpcomingFilingFindings(filingReminders, nowISO)

  // 3. Cert SPV expiry
  const certs = state.certSpvRecords ?? []
  const certSnapshot = certs.length > 0 ? buildCertSnapshot(
    certs.map((c) => recomputeCertStatus(c, nowISO)),
  ) : null
  const certFindings = buildCertExpiryFindings(certs, nowISO)

  // 4. Consistency check (gaps in filings + repeated rectifications)
  const consistencyIssues = checkFilingConsistency(filings)

  // 5. Aggregate
  const allNewFindings: ScanFinding[] = [
    ...overdueFindings,
    ...upcomingFindings,
    ...frequencyFindings,
    ...certFindings,
  ]

  const criticalCount = allNewFindings.filter((f) => f.severity === "critical").length
  const warningCount = allNewFindings.filter((f) => f.severity === "high").length
  const infoCount = allNewFindings.filter(
    (f) => f.severity === "medium" || f.severity === "low",
  ).length

  return {
    scanId,
    scannedAtISO: nowISO,
    summary: {
      totalChecks: 4,
      criticalCount,
      warningCount,
      infoCount,
      newFindingsCount: 0, // populated by route handler after dedup
    },
    expectedFrequency,
    frequencyMismatches,
    filingReminders,
    overdueFindings: [...overdueFindings, ...upcomingFindings],
    frequencyFindings,
    certFindings,
    certSnapshot,
    consistencyIssues,
    newFindings: allNewFindings,
    calendarAutoFill: {
      enabled: autoPopulateCalendar,
      applicableRulesCount,
      autoRecordsGenerated,
      newCount,
      refreshedCount,
      preservedManualCount,
      preservedFiledCount,
      mergedFilings,
    },
  }
}

// ── Idempotent merge helper ──────────────────────────────────────────────────

/**
 * Merge new preventive findings into existing list. Idempotent — re-running
 * scan refreshes existing entries (title, detail, severity) but preserves
 * status + closureEvidence.
 */
export function mergePreventiveFindings(
  existing: ScanFinding[],
  fresh: ScanFinding[],
): { merged: ScanFinding[]; newCount: number; refreshedCount: number } {
  const freshById = new Map<string, ScanFinding>(fresh.map((f) => [f.id, f]))
  let newCount = 0
  let refreshedCount = 0

  const merged: ScanFinding[] = existing.map((f) => {
    const next = freshById.get(f.id)
    if (!next) return f
    freshById.delete(f.id)
    refreshedCount++
    return {
      ...f,
      title: next.title,
      detail: next.detail,
      severity: next.severity,
      risk: next.risk,
      impactSummary: next.impactSummary,
      remediationHint: next.remediationHint,
      legalReference: next.legalReference,
      findingTypeId: next.findingTypeId ?? f.findingTypeId,
    }
  })

  for (const f of freshById.values()) {
    merged.push(f)
    newCount++
  }

  return { merged, newCount, refreshedCount }
}
