// Endpoint agregare calendar fiscal cross-client pentru cabinetul fiscal.
//
// GET → iterează toți clienții din portofoliu, generează calendarul fiecăruia
// pe profilul lui, întoarce agregare:
//   - lista termenelor sortate după dueISO
//   - grupare per termen (ex: D300-Mai apare cu lista clienților afectați)
//   - counts per urgență
//   - top 10 termene urgente
//
// Conservator: dacă un client nu are profil completat, e SKIP fără eroare.

import { NextResponse } from "next/server"

import { jsonError } from "@/lib/server/api-response"
import { AuthzError } from "@/lib/server/auth"
import {
  loadPortfolioBundles,
  requirePortfolioAccess,
  type PortfolioOrgBundle,
} from "@/lib/server/portfolio"
import {
  generateFiscalCalendar,
  inferFiscalProfile,
  type AutoGeneratedFilingRecord,
} from "@/lib/compliance/fiscal-calendar-generator"
import type { FiscalOrgProfile } from "@/lib/compliance/fiscal-calendar-rules"

type ClientCalendarRow = {
  orgId: string
  orgName: string
  record: AutoGeneratedFilingRecord
  daysUntil: number
  urgency: "overdue" | "critical" | "soon" | "future" | "filed"
}

type GroupedDeadline = {
  ruleCode: string
  filingType: string
  period: string
  dueISO: string
  daysUntil: number
  urgency: "overdue" | "critical" | "soon" | "future"
  clients: Array<{ orgId: string; orgName: string; filingId: string; status: string }>
}

type PortfolioCalendarResponse = {
  ok: boolean
  scannedAtISO: string
  summary: {
    totalClients: number
    clientsWithProfile: number
    clientsSkipped: number
    totalDeadlines: number
    overdueCount: number
    criticalCount: number
    soonCount: number
  }
  rows: ClientCalendarRow[]
  grouped: GroupedDeadline[]
  topUrgent: ClientCalendarRow[]
}

function urgencyFromDays(daysUntil: number, status: string): ClientCalendarRow["urgency"] {
  if (status === "on_time" || status === "rectified") return "filed"
  if (status === "missing" || daysUntil < 0) return "overdue"
  if (daysUntil <= 3) return "critical"
  if (daysUntil <= 7) return "soon"
  return "future"
}

export async function GET(request: Request) {
  try {
    const { memberships } = await requirePortfolioAccess(request)
    const bundles = await loadPortfolioBundles(memberships)
    const nowISO = new Date().toISOString()
    const nowMs = new Date(nowISO).getTime()

    const rows: ClientCalendarRow[] = []
    let clientsWithProfile = 0
    let clientsSkipped = 0

    for (const bundle of bundles) {
      const orgProfile = bundle.state?.orgProfile
      if (!orgProfile) {
        clientsSkipped++
        continue
      }
      clientsWithProfile++

      const fiscalProfile = inferFiscalProfile(orgProfile as FiscalOrgProfile)
      const generation = generateFiscalCalendar(fiscalProfile, {
        monthsAhead: 3, // window mai scurt pentru portfolio view
        nowISO,
      })

      // Merge cu filingRecords reale ale clientului (pentru status actualizat)
      const existingByKey = new Map<string, { id: string; status: string }>()
      const existingFilings =
        (bundle.state as typeof bundle.state & {
          filingRecords?: Array<{ id: string; type: string; period: string; status: string }>
        })?.filingRecords ?? []
      for (const f of existingFilings) {
        existingByKey.set(`${f.type}-${f.period}`, { id: f.id, status: f.status })
      }

      for (const record of generation.records) {
        const key = `${record.type}-${record.period}`
        const existing = existingByKey.get(key)
        const status = existing?.status ?? record.status
        const filingId = existing?.id ?? record.id
        const daysUntil = Math.floor((new Date(record.dueISO).getTime() - nowMs) / 86_400_000)

        rows.push({
          orgId: bundle.membership.orgId,
          orgName: bundle.membership.orgName ?? bundle.membership.orgId,
          record: { ...record, id: filingId, status: status as AutoGeneratedFilingRecord["status"] },
          daysUntil,
          urgency: urgencyFromDays(daysUntil, status),
        })
      }
    }

    // Sortăm cronologic
    rows.sort((a, b) => a.record.dueISO.localeCompare(b.record.dueISO))

    // Grupăm per (ruleCode, period) — un termen + lista clienților
    const groupMap = new Map<string, GroupedDeadline>()
    for (const row of rows) {
      if (row.urgency === "filed") continue // doar deadline-uri active
      const key = `${row.record.ruleCode}-${row.record.period}`
      const existing = groupMap.get(key)
      if (existing) {
        existing.clients.push({
          orgId: row.orgId,
          orgName: row.orgName,
          filingId: row.record.id,
          status: row.record.status,
        })
      } else {
        groupMap.set(key, {
          ruleCode: row.record.ruleCode,
          filingType: row.record.type,
          period: row.record.period,
          dueISO: row.record.dueISO,
          daysUntil: row.daysUntil,
          urgency: row.urgency,
          clients: [
            {
              orgId: row.orgId,
              orgName: row.orgName,
              filingId: row.record.id,
              status: row.record.status,
            },
          ],
        })
      }
    }
    const grouped = Array.from(groupMap.values()).sort((a, b) =>
      a.dueISO.localeCompare(b.dueISO),
    )

    // Counts
    let overdueCount = 0
    let criticalCount = 0
    let soonCount = 0
    for (const row of rows) {
      if (row.urgency === "overdue") overdueCount++
      else if (row.urgency === "critical") criticalCount++
      else if (row.urgency === "soon") soonCount++
    }

    const topUrgent = rows
      .filter((r) => r.urgency === "overdue" || r.urgency === "critical")
      .slice(0, 10)

    const response: PortfolioCalendarResponse = {
      ok: true,
      scannedAtISO: nowISO,
      summary: {
        totalClients: bundles.length,
        clientsWithProfile,
        clientsSkipped,
        totalDeadlines: rows.length,
        overdueCount,
        criticalCount,
        soonCount,
      },
      rows: rows.filter((r) => r.urgency !== "filed"), // doar active by default
      grouped,
      topUrgent,
    }

    return NextResponse.json(response)
  } catch (error) {
    if (error instanceof AuthzError) {
      return jsonError(error.message, error.status, error.code)
    }
    return jsonError(
      "Eroare agregare calendar portofoliu.",
      500,
      "PORTFOLIO_CALENDAR_FAILED",
    )
  }
}
