"use client"

// Pagina /dashboard/fiscal/calendar — vedere vizuală a termenelor fiscale
// pentru firma curentă. Timeline cronologic, color-coded urgență, drawer
// per termen cu acțiuni "marchez depus".
//
// Sursa: state.filingRecords (auto-populat din onboarding + preventive-scan).
// Generator: lib/compliance/fiscal-calendar-generator.ts (26 reguli ANAF).

import { useEffect, useMemo, useState } from "react"
import Link from "next/link"
import {
  AlertTriangle,
  ArrowLeft,
  CalendarClock,
  CheckCircle2,
  Clock,
  Filter,
  Loader2,
  RefreshCw,
  Sparkles,
  Wand2,
  XCircle,
} from "lucide-react"
import { toast } from "sonner"

import { V3PageHero } from "@/components/compliscan/v3/page-hero"

type FilingStatus =
  | "on_time"
  | "late"
  | "missing"
  | "rectified"
  | "upcoming"

type FilingRecord = {
  id: string
  type: string
  period: string
  status: FilingStatus
  dueISO: string
  filedAtISO?: string
  note?: string
  autoGenerated?: boolean
  ruleCode?: string
  legalReference?: string
}

type CalendarResponse = {
  ok: boolean
  profile: {
    legalForm: string
    vatRegistered: boolean
    hasEmployees: boolean
    hasIntraCommunityTransactions: boolean
    isMicroenterprise: boolean
    saftCategory: string
  }
  applicableRules: Array<{
    code: string
    shortName: string
    category: string
    legalReference: string
    description: string
    frequency: string
  }>
  records: FilingRecord[]
  situationalRules: Array<{
    code: string
    shortName: string
    description: string
  }>
  summary: {
    totalRules: number
    applicableRules: number
    totalRecords: number
  }
}

const STATUS_LABELS: Record<FilingStatus, string> = {
  on_time: "Depus la timp",
  late: "Depus cu întârziere",
  missing: "Lipsă",
  rectified: "Rectificat",
  upcoming: "Viitor",
}

const FILING_TYPE_LABELS: Record<string, string> = {
  d300_tva: "D300 — Decont TVA",
  d394_local: "D394 — Achiziții/livrări",
  d390_recap: "D390 — Recapitulativă UE",
  saft: "D406 — SAF-T",
  efactura_monthly: "Raport e-Factura B2C",
  etva_precompletata: "e-TVA precompletată",
}

type WindowFilter = "30" | "60" | "90" | "365"
type CategoryFilter = "all" | "tva" | "saft" | "efactura" | "muncitori" | "impozit"
type StatusFilter = "all" | "active" | "upcoming-only" | "overdue-only"

export default function FiscalCalendarPage() {
  const [data, setData] = useState<CalendarResponse | null>(null)
  const [loading, setLoading] = useState(true)
  const [regenerating, setRegenerating] = useState(false)
  const [selectedRecord, setSelectedRecord] = useState<FilingRecord | null>(null)
  const [marking, setMarking] = useState(false)
  const [windowFilter, setWindowFilter] = useState<WindowFilter>("90")
  const [categoryFilter, setCategoryFilter] = useState<CategoryFilter>("all")
  const [statusFilter, setStatusFilter] = useState<StatusFilter>("active")
  const [loadError, setLoadError] = useState<{ message: string; code?: string } | null>(null)

  useEffect(() => {
    void load()
  }, [])

  async function load() {
    setLoading(true)
    setLoadError(null)
    try {
      const res = await fetch("/api/fiscal/calendar/generate?monthsAhead=12", {
        cache: "no-store",
      })
      if (!res.ok) {
        const body = await res.json().catch(() => ({}))
        const message = body.error ?? "Nu am putut încărca calendarul."
        const code = body.code as string | undefined
        setLoadError({ message, code })
        // Nu spammăm toast pe NO_PROFILE — afișăm empty state vizual
        if (code !== "NO_PROFILE") {
          toast.error(message)
        }
        return
      }
      setData((await res.json()) as CalendarResponse)
    } catch (err) {
      const message = err instanceof Error ? err.message : "Eroare."
      setLoadError({ message })
      toast.error(message)
    } finally {
      setLoading(false)
    }
  }

  async function regenerate() {
    setRegenerating(true)
    try {
      const res = await fetch("/api/fiscal/calendar/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ monthsAhead: 12 }),
      })
      if (!res.ok) {
        const body = await res.json().catch(() => ({}))
        toast.error(body.error ?? "Regenerare eșuată.")
        return
      }
      const payload = await res.json()
      toast.success(
        `Calendar actualizat: ${payload.summary.newCount} adăugate, ${payload.summary.refreshedCount} refresh, ${payload.summary.preservedFiledCount} deja depuse.`,
      )
      await load()
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Eroare.")
    } finally {
      setRegenerating(false)
    }
  }

  async function markAsFiled(record: FilingRecord) {
    setMarking(true)
    try {
      const res = await fetch("/api/fiscal/filing-records", {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          id: record.id,
          status: "on_time",
          filedAtISO: new Date().toISOString(),
        }),
      })
      if (!res.ok) {
        const body = await res.json().catch(() => ({}))
        toast.error(body.error ?? "Nu am putut marca ca depus.")
        return
      }
      toast.success(`${FILING_TYPE_LABELS[record.type] ?? record.type} marcat ca depus.`)
      setSelectedRecord(null)
      await load()
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Eroare.")
    } finally {
      setMarking(false)
    }
  }

  const filtered = useMemo(() => {
    if (!data) return []
    const now = new Date()
    const windowDays = parseInt(windowFilter, 10)
    const windowEnd = new Date(now.getTime() + windowDays * 86_400_000)

    return data.records.filter((r) => {
      const due = new Date(r.dueISO)

      // Status filter
      if (statusFilter === "upcoming-only" && r.status !== "upcoming") return false
      if (statusFilter === "overdue-only" && r.status !== "missing") return false
      if (
        statusFilter === "active" &&
        (r.status === "on_time" || r.status === "rectified")
      ) {
        return false
      }

      // Window filter (futures only — overdues always show in active mode)
      if (due > windowEnd) return false

      // Category filter (rough match via ruleCode prefix)
      if (categoryFilter !== "all") {
        const code = r.ruleCode ?? ""
        if (categoryFilter === "tva" && !["D300", "D394", "D390", "D098", "ETVA"].some((c) => code.startsWith(c))) return false
        if (categoryFilter === "saft" && !code.startsWith("D406")) return false
        if (categoryFilter === "efactura" && !code.startsWith("EF-") && code !== "FORM-082") return false
        if (categoryFilter === "muncitori" && !["D112", "D205"].some((c) => code.startsWith(c))) return false
        if (categoryFilter === "impozit" && !["D100", "D101", "D212", "D200", "D230"].some((c) => code.startsWith(c))) return false
      }

      return true
    })
  }, [data, windowFilter, categoryFilter, statusFilter])

  const counts = useMemo(() => {
    if (!data) return { urgent: 0, soon: 0, future: 0, overdue: 0 }
    const now = Date.now()
    let urgent = 0
    let soon = 0
    let future = 0
    let overdue = 0
    for (const r of data.records) {
      const dueMs = new Date(r.dueISO).getTime()
      const daysUntil = Math.floor((dueMs - now) / 86_400_000)
      if (r.status === "missing") overdue++
      else if (daysUntil <= 3 && daysUntil >= 0) urgent++
      else if (daysUntil <= 7 && daysUntil > 3) soon++
      else if (daysUntil > 7) future++
    }
    return { urgent, soon, future, overdue }
  }, [data])

  if (loading) {
    return (
      <div className="space-y-6">
        <V3PageHero
          breadcrumbs={[
            { label: "Firma mea" },
            { label: "Fiscal" },
            { label: "Calendar fiscal", current: true },
          ]}
          title="Calendarul tău fiscal"
          description="Termene ANAF aplicabile firmei tale, generate din profil."
        />
        <div className="flex items-center gap-2 py-12 text-[12.5px] text-eos-text-muted">
          <Loader2 className="size-4 animate-spin" strokeWidth={2} />
          Încarc calendarul fiscal…
        </div>
      </div>
    )
  }

  if (!data) {
    return (
      <div className="space-y-6">
        <V3PageHero
          breadcrumbs={[
            { label: "Firma mea" },
            { label: "Fiscal" },
            { label: "Calendar fiscal", current: true },
          ]}
          title="Calendarul tău fiscal"
          description="Termene ANAF aplicabile firmei tale, generate din profil."
        />
        <section className="rounded-eos-lg border border-eos-border bg-eos-surface p-8 text-center">
          <div className="mx-auto flex max-w-lg flex-col items-center gap-3">
            <div className="flex size-12 items-center justify-center rounded-full border border-eos-warning/30 bg-eos-warning-soft">
              <AlertTriangle className="size-5 text-eos-warning" strokeWidth={2} />
            </div>
            <p
              data-display-text="true"
              className="font-display text-[16px] font-semibold tracking-[-0.015em] text-eos-text"
            >
              {loadError?.code === "NO_PROFILE"
                ? "Profilul firmei nu este complet"
                : "Nu am putut încărca calendarul"}
            </p>
            <p className="text-[12.5px] leading-[1.55] text-eos-text-muted">
              {loadError?.code === "NO_PROFILE"
                ? "Pentru a-ți genera calendarul fiscal personalizat (D300, D406, D205, etc.) avem nevoie să completezi profilul firmei: tip juridic, statut TVA, număr angajați, tranzacții UE."
                : (loadError?.message ?? "A apărut o eroare. Încearcă din nou.")}
            </p>
            <div className="mt-2 flex flex-wrap gap-2">
              {loadError?.code === "NO_PROFILE" && (
                <Link
                  href="/dashboard/setari"
                  className="inline-flex items-center gap-1.5 rounded-eos-md border border-eos-primary bg-eos-primary px-4 py-2 text-[12.5px] font-semibold text-white shadow-eos-sm hover:bg-eos-primary/90"
                >
                  Completează profilul firmei
                </Link>
              )}
              <button
                type="button"
                onClick={load}
                className="inline-flex items-center gap-1.5 rounded-eos-md border border-eos-border bg-eos-surface-elevated px-4 py-2 text-[12.5px] text-eos-text hover:border-eos-border-strong"
              >
                <RefreshCw className="size-3.5" strokeWidth={2} />
                Încearcă din nou
              </button>
            </div>
          </div>
        </section>
        <div className="pt-2">
          <Link
            href="/dashboard/fiscal"
            className="inline-flex items-center gap-1.5 text-[11.5px] text-eos-text-muted hover:text-eos-text"
          >
            <ArrowLeft className="size-3.5" strokeWidth={2} />
            Înapoi la modulul fiscal
          </Link>
        </div>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      <V3PageHero
        breadcrumbs={[
          { label: "Firma mea" },
          { label: "Fiscal" },
          { label: "Calendar fiscal", current: true },
        ]}
        title="Calendarul tău fiscal"
        description={`${data.summary.applicableRules} declarații ANAF aplicabile firmei tale, ${data.summary.totalRecords} termene viitoare pe 12 luni. Generate automat din profil, fără să introduci nimic.`}
        eyebrowBadges={
          <span className="inline-flex items-center gap-1 rounded-sm border border-eos-primary/40 bg-eos-primary-soft px-1.5 py-0.5 font-mono text-[10px] font-semibold uppercase tracking-[0.14em] text-eos-primary">
            <Wand2 className="size-3" strokeWidth={2.5} />
            AUTO-DETECTAT
          </span>
        }
      />

      {/* Provenance banner — transparență totală */}
      <section className="rounded-eos-lg border border-eos-primary/25 bg-eos-primary-soft/40 p-4">
        <div className="flex items-start gap-3">
          <Sparkles className="mt-0.5 size-4 shrink-0 text-eos-primary" strokeWidth={2} />
          <div className="flex-1">
            <p
              data-display-text="true"
              className="font-display text-[13.5px] font-semibold tracking-[-0.015em] text-eos-text"
            >
              Cum am generat acest calendar
            </p>
            <p className="mt-1 text-[12px] leading-[1.6] text-eos-text-muted">
              Aplicăm{" "}
              <strong>26 reguli ANAF publice</strong> (Cod Fiscal, OUG 120/2021,
              Ordine ANAF) pe profilul tău: {data.profile.legalForm}
              {data.profile.vatRegistered ? " · plătitor TVA" : " · neplătitor TVA"}
              {data.profile.hasEmployees ? " · cu angajați" : " · fără angajați"}
              {data.profile.hasIntraCommunityTransactions ? " · cu UE" : ""}. Au
              ieșit <strong>{data.summary.applicableRules} declarații</strong> care
              te privesc — restul (din total {data.summary.totalRules}) nu se aplică
              ție.
            </p>
            <p className="mt-1.5 text-[11px] italic text-eos-text-tertiary">
              Calendarul ANAF e public. Noi îți arătăm doar ce te privește pe tine,
              fără să citești 200 de pagini de lege.
            </p>
          </div>
          <button
            type="button"
            onClick={regenerate}
            disabled={regenerating}
            className="inline-flex items-center gap-1.5 rounded-eos-md border border-eos-border bg-eos-surface px-3 py-1.5 text-[11.5px] font-medium text-eos-text transition hover:border-eos-border-strong disabled:opacity-60"
          >
            {regenerating ? (
              <Loader2 className="size-3.5 animate-spin" strokeWidth={2} />
            ) : (
              <RefreshCw className="size-3.5" strokeWidth={2} />
            )}
            Regenerează
          </button>
        </div>
      </section>

      {/* Summary tiles */}
      <section className="grid grid-cols-2 gap-3 md:grid-cols-4">
        <CountTile
          label="Restante"
          count={counts.overdue}
          tone="critical"
          icon={<XCircle className="size-4" strokeWidth={2} />}
        />
        <CountTile
          label="Urgente (≤3 zile)"
          count={counts.urgent}
          tone="high"
          icon={<AlertTriangle className="size-4" strokeWidth={2} />}
        />
        <CountTile
          label="În curând (≤7 zile)"
          count={counts.soon}
          tone="warning"
          icon={<Clock className="size-4" strokeWidth={2} />}
        />
        <CountTile
          label="Viitoare"
          count={counts.future}
          tone="info"
          icon={<CalendarClock className="size-4" strokeWidth={2} />}
        />
      </section>

      {/* Filters */}
      <section className="flex flex-wrap items-center gap-3 rounded-eos-lg border border-eos-border bg-eos-surface p-3">
        <div className="flex items-center gap-1.5 text-[11.5px] text-eos-text-muted">
          <Filter className="size-3.5" strokeWidth={2} />
          Filtre:
        </div>
        <SelectChip
          label="Fereastră"
          value={windowFilter}
          options={[
            { value: "30", label: "30 zile" },
            { value: "60", label: "60 zile" },
            { value: "90", label: "90 zile" },
            { value: "365", label: "12 luni" },
          ]}
          onChange={(v) => setWindowFilter(v as WindowFilter)}
        />
        <SelectChip
          label="Categorie"
          value={categoryFilter}
          options={[
            { value: "all", label: "Toate" },
            { value: "tva", label: "TVA" },
            { value: "saft", label: "SAF-T" },
            { value: "efactura", label: "e-Factura" },
            { value: "muncitori", label: "Muncă" },
            { value: "impozit", label: "Impozit" },
          ]}
          onChange={(v) => setCategoryFilter(v as CategoryFilter)}
        />
        <SelectChip
          label="Status"
          value={statusFilter}
          options={[
            { value: "active", label: "Active" },
            { value: "upcoming-only", label: "Doar viitoare" },
            { value: "overdue-only", label: "Doar restante" },
            { value: "all", label: "Toate" },
          ]}
          onChange={(v) => setStatusFilter(v as StatusFilter)}
        />
      </section>

      {/* Timeline */}
      <section className="rounded-eos-lg border border-eos-border bg-eos-surface">
        <header className="border-b border-eos-border px-5 py-3">
          <p
            data-display-text="true"
            className="font-display text-[14.5px] font-semibold tracking-[-0.015em] text-eos-text"
          >
            Termene fiscale ({filtered.length})
          </p>
        </header>
        {filtered.length === 0 ? (
          <div className="flex flex-col items-center justify-center gap-2 py-12 text-center">
            <CheckCircle2 className="size-8 text-eos-success" strokeWidth={1.5} />
            <p className="font-display text-[13.5px] font-semibold tracking-[-0.015em] text-eos-text">
              Niciun termen în această fereastră
            </p>
            <p className="max-w-md text-[12px] text-eos-text-muted">
              Schimbă filtrele sau extinde fereastra. Dacă crezi că ar trebui să
              vezi mai multe termene, verifică profilul firmei.
            </p>
          </div>
        ) : (
          <ul className="divide-y divide-eos-border">
            {filtered.map((record) => (
              <CalendarRow
                key={record.id}
                record={record}
                onClick={() => setSelectedRecord(record)}
              />
            ))}
          </ul>
        )}
      </section>

      {/* Situational rules card — afișează ce e situațional, fără termene recurente */}
      {data.situationalRules.length > 0 && (
        <section className="rounded-eos-lg border border-eos-border bg-eos-surface p-5">
          <p
            data-display-text="true"
            className="font-display text-[13.5px] font-semibold tracking-[-0.015em] text-eos-text"
          >
            Situaționale aplicabile (fără termene fixe)
          </p>
          <p className="mt-1 text-[11.5px] text-eos-text-muted">
            Aceste declarații se aplică doar la eveniment (înregistrare, modificare
            vector fiscal, schimbare frecvență TVA). Le ținem minte ca să te
            avertizăm când se aplică situația.
          </p>
          <ul className="mt-3 space-y-1.5">
            {data.situationalRules.map((rule) => (
              <li
                key={rule.code}
                className="rounded-eos-md border border-eos-border bg-eos-surface-elevated px-3 py-2 text-[12px]"
              >
                <p className="font-semibold text-eos-text">{rule.shortName}</p>
                <p className="mt-0.5 text-[11px] text-eos-text-muted">
                  {rule.description}
                </p>
              </li>
            ))}
          </ul>
        </section>
      )}

      {/* Drawer */}
      {selectedRecord && (
        <RecordDrawer
          record={selectedRecord}
          rule={data.applicableRules.find((r) => r.code === selectedRecord.ruleCode)}
          onClose={() => setSelectedRecord(null)}
          onMarkAsFiled={() => markAsFiled(selectedRecord)}
          marking={marking}
        />
      )}

      <div className="pt-2">
        <Link
          href="/dashboard/fiscal"
          className="inline-flex items-center gap-1.5 text-[11.5px] text-eos-text-muted hover:text-eos-text"
        >
          <ArrowLeft className="size-3.5" strokeWidth={2} />
          Înapoi la modulul fiscal
        </Link>
      </div>
    </div>
  )
}

// ── Sub-components ───────────────────────────────────────────────────────────

function CountTile({
  label,
  count,
  tone,
  icon,
}: {
  label: string
  count: number
  tone: "critical" | "high" | "warning" | "info"
  icon: React.ReactNode
}) {
  const toneClass =
    tone === "critical"
      ? "border-eos-error/40 bg-eos-error-soft text-eos-error"
      : tone === "high"
        ? "border-eos-warning/40 bg-eos-warning-soft text-eos-warning"
        : tone === "warning"
          ? "border-eos-primary/30 bg-eos-primary-soft text-eos-primary"
          : "border-eos-border bg-eos-surface text-eos-text"
  return (
    <div className={`flex items-center gap-3 rounded-eos-lg border px-4 py-3 ${toneClass}`}>
      {icon}
      <div>
        <p className="font-display text-[22px] font-bold leading-none">{count}</p>
        <p className="mt-0.5 font-mono text-[10px] uppercase tracking-[0.14em] opacity-70">
          {label}
        </p>
      </div>
    </div>
  )
}

function SelectChip({
  label,
  value,
  options,
  onChange,
}: {
  label: string
  value: string
  options: Array<{ value: string; label: string }>
  onChange: (value: string) => void
}) {
  return (
    <label className="flex items-center gap-1.5 text-[11.5px]">
      <span className="text-eos-text-muted">{label}:</span>
      <select
        value={value}
        onChange={(e) => onChange(e.target.value)}
        className="rounded-eos-sm border border-eos-border bg-eos-surface-elevated px-2 py-1 text-[11.5px] text-eos-text focus:border-eos-primary focus:outline-none"
      >
        {options.map((opt) => (
          <option key={opt.value} value={opt.value}>
            {opt.label}
          </option>
        ))}
      </select>
    </label>
  )
}

function CalendarRow({
  record,
  onClick,
}: {
  record: FilingRecord
  onClick: () => void
}) {
  const due = new Date(record.dueISO)
  const now = new Date()
  const daysUntil = Math.floor((due.getTime() - now.getTime()) / 86_400_000)

  const isOverdue = record.status === "missing"
  const isFiled = record.status === "on_time" || record.status === "rectified"

  let tone: "critical" | "high" | "warning" | "info" | "success" = "info"
  let urgencyLabel = ""

  if (isFiled) {
    tone = "success"
    urgencyLabel = "DEPUS"
  } else if (isOverdue) {
    tone = "critical"
    urgencyLabel = `RESTANT cu ${Math.abs(daysUntil)} zile`
  } else if (daysUntil <= 3) {
    tone = "high"
    urgencyLabel = daysUntil === 0 ? "ASTĂZI" : daysUntil === 1 ? "MÂINE" : `${daysUntil} zile`
  } else if (daysUntil <= 7) {
    tone = "warning"
    urgencyLabel = `${daysUntil} zile`
  } else {
    urgencyLabel = `${daysUntil} zile`
  }

  const toneClass =
    tone === "critical"
      ? "border-l-eos-error"
      : tone === "high"
        ? "border-l-eos-warning"
        : tone === "warning"
          ? "border-l-eos-primary"
          : tone === "success"
            ? "border-l-eos-success"
            : "border-l-eos-border"

  return (
    <li>
      <button
        type="button"
        onClick={onClick}
        className={`flex w-full items-center justify-between gap-3 border-l-2 px-5 py-3 text-left transition hover:bg-eos-surface-elevated ${toneClass}`}
      >
        <div className="min-w-0 flex-1">
          <div className="flex items-center gap-2">
            <p className="font-semibold text-[13px] text-eos-text">
              {FILING_TYPE_LABELS[record.type] ?? record.type}
            </p>
            {record.autoGenerated && (
              <span className="inline-flex items-center gap-0.5 rounded-eos-sm border border-eos-primary/30 bg-eos-primary-soft px-1.5 py-0.5 font-mono text-[9.5px] font-semibold uppercase tracking-[0.12em] text-eos-primary">
                <Wand2 className="size-2.5" strokeWidth={2.5} />
                AUTO
              </span>
            )}
          </div>
          <p className="mt-0.5 text-[11.5px] text-eos-text-muted">
            Perioada {record.period} · Termen {due.toLocaleDateString("ro-RO", { day: "numeric", month: "long", year: "numeric" })}
          </p>
        </div>
        <div className="text-right shrink-0">
          <span
            className={`font-mono text-[10.5px] font-bold uppercase tracking-[0.12em] ${
              tone === "critical"
                ? "text-eos-error"
                : tone === "high"
                  ? "text-eos-warning"
                  : tone === "warning"
                    ? "text-eos-primary"
                    : tone === "success"
                      ? "text-eos-success"
                      : "text-eos-text-muted"
            }`}
          >
            {urgencyLabel}
          </span>
          <p className="mt-0.5 text-[10px] text-eos-text-tertiary">
            {STATUS_LABELS[record.status]}
          </p>
        </div>
      </button>
    </li>
  )
}

function RecordDrawer({
  record,
  rule,
  onClose,
  onMarkAsFiled,
  marking,
}: {
  record: FilingRecord
  rule?: { code: string; shortName: string; description: string; legalReference: string; frequency: string }
  onClose: () => void
  onMarkAsFiled: () => void
  marking: boolean
}) {
  const due = new Date(record.dueISO)
  const isFiled = record.status === "on_time" || record.status === "rectified"

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"
      onClick={onClose}
    >
      <div
        className="w-full max-w-lg rounded-eos-lg border border-eos-border bg-eos-surface p-6 shadow-xl"
        onClick={(e) => e.stopPropagation()}
      >
        <header className="flex items-start justify-between gap-3">
          <div>
            <p className="font-display text-[16px] font-semibold tracking-[-0.015em] text-eos-text">
              {FILING_TYPE_LABELS[record.type] ?? record.type}
            </p>
            <p className="mt-0.5 text-[12px] text-eos-text-muted">
              Perioada {record.period}
            </p>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="rounded-eos-sm border border-eos-border bg-eos-surface-elevated p-1 text-eos-text-muted hover:border-eos-border-strong"
          >
            <XCircle className="size-4" strokeWidth={2} />
          </button>
        </header>

        <dl className="mt-4 space-y-2.5">
          <DrawerRow
            label="Termen"
            value={due.toLocaleDateString("ro-RO", {
              weekday: "long",
              day: "numeric",
              month: "long",
              year: "numeric",
            })}
          />
          <DrawerRow label="Status" value={STATUS_LABELS[record.status]} />
          {rule && (
            <>
              <DrawerRow label="Cod ANAF" value={rule.code} />
              <DrawerRow label="Frecvență" value={rule.frequency} />
              <DrawerRow label="Temei legal" value={rule.legalReference} />
              <DrawerRow label="Ce e" value={rule.description} multiline />
            </>
          )}
          {record.note && (
            <DrawerRow label="Notă" value={record.note} multiline />
          )}
        </dl>

        {!isFiled && (
          <div className="mt-5 flex gap-2">
            <button
              type="button"
              onClick={onMarkAsFiled}
              disabled={marking}
              className="flex-1 inline-flex items-center justify-center gap-1.5 rounded-eos-md border border-eos-primary bg-eos-primary px-3 py-2 text-[12.5px] font-medium text-white shadow-eos-sm hover:bg-eos-primary/90 disabled:opacity-60"
            >
              {marking ? (
                <Loader2 className="size-3.5 animate-spin" strokeWidth={2} />
              ) : (
                <CheckCircle2 className="size-3.5" strokeWidth={2.5} />
              )}
              Marchez ca depus
            </button>
            <button
              type="button"
              onClick={onClose}
              className="rounded-eos-md border border-eos-border bg-eos-surface-elevated px-3 py-2 text-[12.5px] text-eos-text-muted hover:border-eos-border-strong"
            >
              Anulează
            </button>
          </div>
        )}

        {isFiled && record.filedAtISO && (
          <div className="mt-5 space-y-2">
            <div className="flex items-center gap-2 rounded-eos-md border border-eos-success/30 bg-eos-success-soft px-3 py-2 text-[12px] text-eos-success">
              <CheckCircle2 className="size-4 shrink-0" strokeWidth={2} />
              Depus la {new Date(record.filedAtISO).toLocaleDateString("ro-RO")}
            </div>
            {parseConfirmationSource(record.note) && (
              <div className="flex items-center gap-2 rounded-eos-md border border-eos-primary/30 bg-eos-primary-soft px-3 py-2 text-[12px] text-eos-primary">
                <Sparkles className="size-4 shrink-0" strokeWidth={2} />
                <span>
                  Confirmat automat din{" "}
                  <strong>{parseConfirmationSource(record.note)}</strong>
                </span>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  )
}

/**
 * Parsează note pentru a extrage sursa confirmării.
 * Format așteptat (scris de applyFilingConfirmation):
 *   "[Confirmat din SmartBill (ref: SB-123) la 2026-06-20] — opt. notă"
 */
function parseConfirmationSource(note: string | undefined): string | null {
  if (!note) return null
  const match = /\[Confirmat din ([^\(\]]+?)(?:\s*\(|\s*\])/i.exec(note)
  if (!match) return null
  return match[1]?.trim() ?? null
}

function DrawerRow({
  label,
  value,
  multiline = false,
}: {
  label: string
  value: string
  multiline?: boolean
}) {
  return (
    <div className={multiline ? "" : "flex items-baseline gap-3"}>
      <dt className="font-mono text-[10px] font-semibold uppercase tracking-[0.14em] text-eos-text-tertiary shrink-0">
        {label}
      </dt>
      <dd className={`text-[12px] text-eos-text ${multiline ? "mt-1" : ""}`}>
        {value}
      </dd>
    </div>
  )
}
